---

- name: Get start timestmp
  hosts: deploy
  connection: local
  tasks:
    - set_fact:
        starttime: "{{ ansible_date_time }}"

- name: Prepare repo and ironic related rpms
  hosts: inhostmg
  user: root
  vars_files:
    - "vars/deploy.yml"
  roles:
    - prepare

- name: Setup database
  hosts: inhostmg
  user: root
  vars_files:
    - "vars/deploy.yml"
  roles:
    - db

- name: Setup message queue server
  hosts: inhostmg
  user: root
  vars_files:
    - "vars/deploy.yml"
  roles:
    - mq

- name: Setup ironic
  hosts: inhostmg
  user: root
  vars_files:
    - "vars/deploy.yml"
  roles:
    - ironic

- name: Setup ironic-inspector
  hosts: inhostmg
  user: root
  vars_files:
    - "vars/deploy.yml"
  roles:
    - inspector

- name: Inform the installer
  hosts: deploy
  connection: local
  tasks:
    - debug:
        msg: >-
          The deploy started at {{ hostvars.deploy.starttime.time }},
          ended at {{ ansible_date_time.time }}
