---

# Already install these packages cause of mysql_db use.
- name: Install related packages for mariadb
  yum:
    name: "{{ item }}"
    state: latest
  with_items:
    - mariadb
    - mariadb-server
    - python2-PyMySQL
    - MySQL-python

- name: Create openstack db configuration
  template:
    src: roles/db/templates/openstack.cnf.j2
    dest: "/etc/my.cnf.d/openstack.cnf"

- name: Start mariadb service
  service:
    name: mariadb
    enabled: yes
    state: started

- include: mysql_secure_installation.yml
